
"""bottle_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYAwSYJIoIrm6zn3omJveJ20MtqP7a7G
"""

!nvidia-smi

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/Bottle_Detection

!yolo task=detect mode = train model = yolov8s.pt data = /content/drive/MyDrive/Bottle_Detection/bottle-detection/bottle/data.yaml epochs =25 imgsz = 224 plots = True

!yolo task=detect mode = val model = runs/detect/train6/weights/best.pt data = /content/drive/MyDrive/Bottle_Detection/bottle-detection/bottle/data.yaml

!yolo task=detect mode =predict model = runs/detect/train6/weights/best.pt  conf = 0.25 source = /content/drive/MyDrive/Bottle_Detection/bottle-detection/bottle/data/test/images
